config/routes.rb
Rails.application.routes.draw do
  root 'page#home'
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }
  resources :questions, only: [:index]
  resources :users
  resources :assessments
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  has_many :questions, dependent: :destroy

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :title, uniqueness: true
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_assessment, only: %w[:show, :edit, :update, :destroy]

  def create
    @assessment = Assessment.new(assessment_params)
    if @assessment.save
      redirect_to @assessment
    else
      render :new
    end
  end

  def new
    @assessment = Assessment.new
  end

  def index
    @assessment = Assessment.all
  end

  def show
    #if @assessment.blank?
    #redirect_to assessment_path
    #else
    #@questions = @assessment.questions
    #end
  end

  def edit
  end


  def destroy
    @assessment = Assessment.find(params[:id])
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to assessments_url, notice: 'Assessment was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private

  def set_assessment
    @assessment = Assessment.find(params[:id])
  end

  def assessment_params
    params.require(:assessment).permit(:title, :_destroy, questions_attributes: [:id, :text, variants_attributes: [:id, :text, :value, :_destroy] ])
  end

end

app/views/assessments/_question.html.haml
.nested-fields
  .field.question
    %h3 Question
    = f.text_field :text
    .variants
      = f.fields_for :variants do |variant|
        = render 'variant_fields', f: variant
    .links
      = link_to_remove_association "remove question", f
      = link_to_add_association 'add variant', f, :variants

app/views/assessments/_variant.html.haml
.nested-fields
  = f.text_field :text
  = f.text_field :value
  = link_to_remove_association "remove variant", f

app/views/assessments/_variant_fields.html.haml
.nested-fields
  %h3 Variant
  = f.text_field :text
  %h3 Variant value
  = f.number_field :value
  = link_to_remove_association "remove variant", f

app/views/assessments/index.html.erb
<% provide(:title, 'All assessments') %>
<nav class="navbar navbar-expand-sm bg-light">
</nav>
<h1>All assessments</h1>
  <ul class="assessments">
    <% @assessments.each do |assessment| %>
      <li>
        <td><%= assessment.title %></td>
        <td><%= link_to 'Show', assessment %></td>
        <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
        <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </li>
    <% end %>
  </ul>

app/views/assessments/new.html.haml
= form_for @assessment do |f|
  = f.label :name_assessment
  = f.text_field :title
  #questions
    = f.fields_for :questions, @assessment.questions.build do |question|
      %h3 Questions
      = render 'question', f: question
      .links
      = link_to_add_association 'Add Question', f, :questions, partial: 'question'
      .action
    =f.submit "Create"

app/views/assessments/show.html.haml
%h1
  = @assessment.title
- @questions.each_with_index do |q, index|
  %span= index + 1
  %span= q.text
  - q.variants.each do |v|
    %p Variant
    %span= v.text
    %span= v.value